# Travis-CI.org build script

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.

dist: trusty

# use containerized infrastructure (for faster startup; no sudo)
sudo: false


language: cpp

compiler:
  - gcc
  - clang

script:
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - ./test-intensity-hdf5-file
    - ./test-misc
    - ./test-network-streams

addons:
  apt:
    packages:
      - libhdf5-serial-dev

