# Travis-CI.org build script

# Default environment is Ubuntu 12.04.5 LTS "precise"
# which is pretty old.
# (gcc 4.6.3, which doesn't know about -std=c++11
#  and fails with
#  ch_frb_io.hpp:279:28: sorry, unimplemented: non-static data member initializers
#  ch_frb_io.hpp:279:28: error: ISO C++ forbids in-class initialization of non-const static member 'udp_port'

# "trusty" is Ubuntu 14.04.5 LTS
# gcc 4.8.4

dist: trusty

# use containerized infrastructure (for faster startup; no sudo)
sudo: false

language: cpp

compiler:
  - gcc
  - clang

script:
    - pwd
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/chime/lib
    - ln -s site/Makefile.local.travis Makefile.local
    - make
    - make install
    - ./test-intensity-hdf5-file yes
    - ./test-misc
    # Takes an hour...
    # - ./test-network-streams

addons:
  apt:
    packages:
      - libhdf5-serial-dev

